name: schismviz
channels:
  - conda-forge
  - cadwr-dms
dependencies:
  - python=3.13
  - ipykernel #=6.17.1
  - metpy
  - schimpy
  - numpy
  - xarray  
  - pandas
  - hvplot
  - ipywidgets
  #- trame
  #- pyvista # 3D plots
  - cartopy
  - shapely
  - geopandas
  - geoviews
  - spatialpandas
  - bokeh
  - plotly
  - matplotlib
  - scikit-learn
  - lxml
  - html5lib
